# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Testing Apk

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 3.29.2
    - run: flutter pub get
    - run: flutter build apk
    # - run: flutter build appbundle
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: AceVocab-debug.apk  # A descriptive name for the artifact.
        path: build/app/outputs/flutter-apk/app-debug.apk  # Correct path to the APK.
        if-no-files-found: error # Error if apk is not found.
        retention-days: 3       # Keep the artifact for 5 days.
